# Generated by Django 5.2.8 on 2025-11-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la propiedad')),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('estacionamiento', 'Estacionamiento')], max_length=20, verbose_name='Tipo de propiedad')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('metros_cuadrados', models.PositiveIntegerField(verbose_name='Metros cuadrados')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible para arrendar')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='propiedades/', verbose_name='Foto de la propiedad')),
            ],
        ),
    ]
