# Generated by Django 5.2.8 on 2025-11-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='dormitorios',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de dormitorios'),
        ),
    ]
